// Code generated by "stringer -type CntType ./"; DO NOT EDIT

package agiledoc

import "fmt"

const _CntType_name = "LIST_ARRAYLIST_SINGLELIST_DOUBLESET_HASHSET_TREESTACK_LINKEDSTACK_ARRAYMAP_HASHMAP_HASHBIDIMAP_TREEMAP_TREEBIDITREE_REDBLACKTREE_BINHEAP"

var _CntType_map = map[CntType]string{
	1:    _CntType_name[0:10],
	2:    _CntType_name[10:21],
	4:    _CntType_name[21:32],
	8:    _CntType_name[32:40],
	16:   _CntType_name[40:48],
	32:   _CntType_name[48:60],
	64:   _CntType_name[60:71],
	128:  _CntType_name[71:79],
	256:  _CntType_name[79:91],
	512:  _CntType_name[91:99],
	1024: _CntType_name[99:111],
	2048: _CntType_name[111:124],
	4096: _CntType_name[124:136],
}

func (i CntType) String() string {
	if str, ok := _CntType_map[i]; ok {
		return str
	}
	return fmt.Sprintf("CntType(%d)", i)
}
