// Code generated by "stringer -type CntType ./"; DO NOT EDIT

package agiledoc

import "fmt"

const _CntType_name = "CONTAINERLIST_ARRAYLIST_SINGLELIST_DOUBLESET_HASHSET_TREESTACK_LINKEDSTACK_ARRAYMAP_HASHMAP_HASHBIDIMAP_TREEMAP_TREEBIDITREE_REDBLACKTREE_BINHEAP"

var _CntType_map = map[CntType]string{
	0:    _CntType_name[0:9],
	1:    _CntType_name[9:19],
	2:    _CntType_name[19:30],
	4:    _CntType_name[30:41],
	8:    _CntType_name[41:49],
	16:   _CntType_name[49:57],
	32:   _CntType_name[57:69],
	64:   _CntType_name[69:80],
	128:  _CntType_name[80:88],
	256:  _CntType_name[88:100],
	512:  _CntType_name[100:108],
	1024: _CntType_name[108:120],
	2048: _CntType_name[120:133],
	4096: _CntType_name[133:145],
}

func (i CntType) String() string {
	if str, ok := _CntType_map[i]; ok {
		return str
	}
	return fmt.Sprintf("CntType(%d)", i)
}
