// Code generated by "stringer -type Number ./"; DO NOT EDIT

package agiledoc

import "fmt"

const (
	_Number_name_0 = "zero"
	_Number_name_1 = "onetwothreefourfivesixseveneightnineteneleventwelvethirteen"
	_Number_name_2 = "twen"
	_Number_name_3 = "hundred"
	_Number_name_4 = "thousend"
	_Number_name_5 = "million"
	_Number_name_6 = "billion"
	_Number_name_7 = "trillion"
)

var (
	_Number_index_0 = [...]uint8{0, 4}
	_Number_index_1 = [...]uint8{0, 3, 6, 11, 15, 19, 22, 27, 32, 36, 39, 45, 51, 59}
	_Number_index_2 = [...]uint8{0, 4}
	_Number_index_3 = [...]uint8{0, 7}
	_Number_index_4 = [...]uint8{0, 8}
	_Number_index_5 = [...]uint8{0, 7}
	_Number_index_6 = [...]uint8{0, 7}
	_Number_index_7 = [...]uint8{0, 8}
)

func (i Number) String() string {
	switch {
	case i == 0:
		return _Number_name_0
	case 2 <= i && i <= 14:
		i -= 2
		return _Number_name_1[_Number_index_1[i]:_Number_index_1[i+1]]
	case i == 20:
		return _Number_name_2
	case i == 100:
		return _Number_name_3
	case i == 1000:
		return _Number_name_4
	case i == 1000000:
		return _Number_name_5
	case i == 1000000000:
		return _Number_name_6
	case i == 1000000000000:
		return _Number_name_7
	default:
		return fmt.Sprintf("Number(%d)", i)
	}
}
