// Code generated by "stringer -type Reserved"; DO NOT EDIT

package agiledoc

import "fmt"

const _Reserved_name = "BLANK"

var _Reserved_index = [...]uint8{0, 5}

func (i Reserved) String() string {
	i -= 32
	if i >= Reserved(len(_Reserved_index)-1) {
		return fmt.Sprintf("Reserved(%d)", i+32)
	}
	return _Reserved_name[_Reserved_index[i]:_Reserved_index[i+1]]
}
