// Code generated by "stringer -type ValueType ."; DO NOT EDIT

package agiledoc

import "fmt"

const (
	_ValueType_name_0 = "EMPTY"
	_ValueType_name_1 = "BOOL"
	_ValueType_name_2 = "INTEGER"
	_ValueType_name_3 = "FLOAT"
	_ValueType_name_4 = "BYTE"
	_ValueType_name_5 = "BYTES"
	_ValueType_name_6 = "STRING"
	_ValueType_name_7 = "VECTOR"
	_ValueType_name_8 = "MATRIX"
)

var (
	_ValueType_index_0 = [...]uint8{0, 5}
	_ValueType_index_1 = [...]uint8{0, 4}
	_ValueType_index_2 = [...]uint8{0, 7}
	_ValueType_index_3 = [...]uint8{0, 5}
	_ValueType_index_4 = [...]uint8{0, 4}
	_ValueType_index_5 = [...]uint8{0, 5}
	_ValueType_index_6 = [...]uint8{0, 6}
	_ValueType_index_7 = [...]uint8{0, 6}
	_ValueType_index_8 = [...]uint8{0, 6}
)

func (i ValueType) String() string {
	switch {
	case i == 0:
		return _ValueType_name_0
	case i == 2:
		return _ValueType_name_1
	case i == 4:
		return _ValueType_name_2
	case i == 8:
		return _ValueType_name_3
	case i == 16:
		return _ValueType_name_4
	case i == 32:
		return _ValueType_name_5
	case i == 64:
		return _ValueType_name_6
	case i == 128:
		return _ValueType_name_7
	case i == 256:
		return _ValueType_name_8
	default:
		return fmt.Sprintf("ValueType(%d)", i)
	}
}
